/**
 * golden.record.js — regenerate tests/golden.json.
 *
 *   node tests/golden.record.js          write the file
 *   node tests/golden.record.js --diff   show what would change, write nothing
 *
 * Run this ONLY when a behaviour change was intended and is covered by an ADR.
 * Always inspect the diff before committing. See the header of golden.test.js.
 */
const fs = require('node:fs');
const path = require('node:path');
const { ModelModule } = require('../tools/load-model');
const BASE = require('../tools/baseline-inputs');
const { SCENARIOS, summarise } = require('./golden.scenarios');

const OUT = path.join(__dirname, 'golden.json');
const diffOnly = process.argv.includes('--diff');

const scenarios = {};
for (const [name, over] of Object.entries(SCENARIOS)) {
  scenarios[name] = summarise(ModelModule.calculate({ ...BASE, ...over }));
}

const next = {
  _comment: 'Generated by tests/golden.record.js. Do not hand-edit. See golden.test.js.',
  recordedAt: new Date().toISOString().slice(0, 10),
  scenarios,
};

if (fs.existsSync(OUT)) {
  const prev = JSON.parse(fs.readFileSync(OUT, 'utf8'));
  const changes = [];
  for (const [name, want] of Object.entries(scenarios)) {
    const had = prev.scenarios?.[name];
    if (!had) { changes.push(`+ NEW SCENARIO  ${name}`); continue; }
    for (const key of Object.keys(want)) {
      if (JSON.stringify(had[key]) !== JSON.stringify(want[key])) {
        const pct = typeof had[key] === 'number' && had[key] !== 0
          ? `  (${((want[key] - had[key]) / Math.abs(had[key]) * 100).toFixed(2)}%)` : '';
        changes.push(`  ${name} :: ${key}: ${JSON.stringify(had[key])} -> ${JSON.stringify(want[key])}${pct}`);
      }
    }
  }
  for (const name of Object.keys(prev.scenarios ?? {})) {
    if (!scenarios[name]) changes.push(`- REMOVED SCENARIO  ${name}`);
  }

  if (changes.length === 0) {
    console.log('No behaviour change. golden.json is already current.');
    if (!diffOnly) console.log('Nothing written.');
    process.exit(0);
  }

  console.log(`${changes.length} value(s) would change:\n`);
  console.log(changes.join('\n'));
  console.log('');
  if (diffOnly) { console.log('--diff: nothing written.'); process.exit(1); }
  console.log('Confirm each move matches the prediction in your ADR before committing.\n');
}

fs.writeFileSync(OUT, JSON.stringify(next, null, 2) + '\n', 'utf8');
console.log(`Wrote ${OUT} (${Object.keys(scenarios).length} scenarios).`);
